[colors.primary]
background = '#070b14'
foreground = '#e6edf7'

[colors.selection]
text = '#e6edf7'
background = '#3a1620'

[colors.cursor]
text = '#070b14'
cursor = '#ff4e66'

[colors.normal]
black   = '#0b0f1a'
red     = '#ff3c3f'
green   = '#76ff4e'
yellow  = '#ffd83c'
blue    = '#f62e46'
magenta = '#760010'
cyan    = '#ff4e66'
white   = '#ffe9ec'

[colors.bright]
black   = '#a59496'
red     = '#ff7a7c'
green   = '#9fff83'
yellow  = '#ffe683'
blue    = '#ff687c'
magenta = '#ff8393'
cyan    = '#ffafba'
white   = '#fff6f7'
